version: '3'
services:
  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:latest
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - helium-miner
    environment:
      MODEL: 'AUTO'
      BAND: 'eu_863_870'
      DEVICE: '/dev/spidev1.0'
      USE_LIBGPIOD: 0
      RESET_GPIO: 149
      POWER_EN_GPIO: 125
      SERVER_HOST: '127.0.0.1'
      SERVER_PORT: 1680

  helium-miner:
    image: quay.io/team-helium/miner:gateway-latest
    command: ["helium_gateway", "server"]
    environment:
      - GW_REGION=EU868
      - RUST_BACKTRACE=1
      - GW_LISTEN=0.0.0.0:1680
      - GW_KEYPAIR=ecc://i2c-2:96?slot=0
      - GW_ONBOARDING=ecc://i2c-2:96?slot=15
    privileged: true
    devices:
      - /dev/i2c-2:/dev/i2c-2
    network_mode: host
    restart: unless-stopped
