version: '3'
services:
  pktfwd:
    image: ghcr.io/heliumdiy/sx1302_hal:sha-87d8931
    entrypoint: ["/opt/packet_forwarder/entrypoint.sh"]
    working_dir: /opt/packet_forwarder
    environment:
      VENDOR: bobcat
      REGION: EU868
    privileged: true
    depends_on:
      - helium-miner
    volumes:
      - ./packet_forwarder/configs:/opt/packet_forwarder/configs
      - ./packet_forwarder/tools:/opt/packet_forwarder/tools
    network_mode: host
    restart: always

  miner:
    image: quay.io/team-helium/miner:gateway-latest
    command: ["helium_gateway", "server"]
    environment:
      - GW_REGION=EU868
      - RUST_BACKTRACE=1
      - GW_LISTEN=0.0.0.0:1680
      - GW_KEYPAIR=ecc://i2c-2:96?slot=0
      - GW_ONBOARDING=ecc://i2c-2:96?slot=15
    privileged: true
    devices:
      - /dev/i2c-2:/dev/i2c-2
    security_opt:
      - label=disable
    network_mode: host
    restart: unless-stopped

